### ISSUE TITLE
Importing SVG doesn't import all "parts"

### ISSUE THREAD

**Issue by reltham** [LightBurnSoftware/Documentation#10]
When Importing and SVG file it only imports one of the parts (not sure that is the right term here).  

I can Open the same SVG file and it will load all the parts.

I've attached an example SVG that exhibits this issue.

[xmas_tree_lightup.zip](https://github.com/LightBurnSoftware/Documentation/files/1595106/xmas_tree_lightup.zip)

**Comment by reltham** [comment]
Sorry if this is not a good place to report issues with the software. Feel free to nuke this and my other issue from here if they don't go here.

**Comment by gndprx** [comment]
Hi reltham.

You may get better response from here: https://www.facebook.com/groups/1190357787764055/

This particular Git repo is for tracking the documentation portion of the application and probably wont' get the intended response. 

Thanks.
