### ISSUE TITLE
Ruida

### ISSUE THREAD

**Issue by gaddcasey1** [LightBurnSoftware/Documentation#11]
how do you set a reverse interval? This is used in RDworks to correct double images when engraving.  

![rdworks](https://user-images.githubusercontent.com/5962334/34705658-dace03a0-f4b6-11e7-8edf-4f2e25d9e736.png)

![engrave](https://user-images.githubusercontent.com/5962334/34705662-e303462a-f4b6-11e7-9efe-89a703f0806f.png)

**Comment by LightBurnSoftware** [comment]
At the moment, you don't, but the feature is partially implemented already. Expect another week or two for completion.

**Comment by funinthefalls** [comment]
If you have any more questions, the LightBurn Facebook page is the best place to ask.
