### ISSUE TITLE
API? Macros?

### ISSUE THREAD

**Issue by gaddcasey1** [LightBurnSoftware/Documentation#12]
I would love to create some custom buttons to run scripted tasks.

**Comment by LightBurnSoftware** [comment]
We have, longer term, a plan to add Python to the system. "scripted tasks" opens up a lot of potential issues, so we would need to be very careful with the implementation. Can you give an example of your target case?

**Comment by LightBurnSoftware** [comment]
Also, we don't check these often - the Facebook or GooglePlus pages are much better for this.
