### ISSUE TITLE
Debug Drawing

### ISSUE THREAD

**Issue by KnottyWood** [LightBurnSoftware/Documentation#13]
Can't find info regarding the use of 'Debug Drawing' in current docs. #5

**Comment by LightBurnSoftware** [comment]
Debug Drawing is simply an option to render the bounds and vertices of shapes. It is intended as a developer tool, nothing more.

**Comment by funinthefalls** [comment]
If you have any more questions, the LightBurn Facebook page is the best place to ask.

**Comment by KnottyWood** [comment]
Thanks for the comment on issues 13 #funinthefalls. Have things changed?

Back on January 11 at 2:35pm, I posted the following on said support page: https://www.facebook.com/groups/1190357787764055/permalink/1199095780223589/

You will notice that the first response from the team directed me as follows, "LightBurn
Group Admin - For docs issues, you can submit an issue on GitHub itself. On the other hand, you can send anything to developer at LightBurnSoftware.com and it’ll get where it needs to go."

If things have changed and to best help the overall LB effort, might I suggest someone from the team pin a post directing current 'best practices' and desired repositories for reporting issues, asking questions, et. al. for all of us to follow.

Same applies to issue #14

**Comment by LightBurnSoftware** [comment]
The FB support page is generally the best place to post, so the above is more of a stock response when closing a ticket.

**Comment by KnottyWood** [comment]
Ah, got it!

**Comment by LightBurnSoftware** [comment]
We’re also looking into the feasibility of setting up a dedicated forum, as that would allow much easier pinning, FAQs, and topic searching. The FB page is getting a bit untenable.

**Comment by KnottyWood** [comment]
Truedat!!! Keep up the great workx!
