### ISSUE TITLE
Convert to Cut

### ISSUE THREAD

**Issue by KnottyWood** [LightBurnSoftware/Documentation#14]
Can't find info regarding the use of 'Convert to Cut' in current docs. #5

**Comment by LightBurnSoftware** [comment]
Similar to Debug Drawing, this is a developer tool. It converts the current selection to the set of paths generated by the cut builder - scans will be converted into a series of raster lines, curves are converted to line segments. The result is stored as a shape and inserted into the scene over the original shapes, to allow us to check the accuracy of conversion.

**Comment by KnottyWood** [comment]
Got it.  I guess these menu options will disappear at some point as to not confuse the newbies like me! ;) Just trying to follow the 'see something, say something' approach in hopes of helping this awesome project.

**Comment by LightBurnSoftware** [comment]
Much appreciated - at the very least we should note these options in the docs.

**Comment by gndprx** [comment]
Yep, I fell into that trap when I first started using it too. I thought those options were going to be yanked out of the menu but we can add something about them in the documentation somewhere. Just need to figure out where makes the most sense.

**Comment by funinthefalls** [comment]
If you have any more questions, the LightBurn Facebook page is the best place to ask.
