### ISSUE TITLE
Starting Point Issue

### ISSUE THREAD

**Issue by 3t-design** [LightBurnSoftware/Documentation#15]
When I put my starting point at the lower right corner and creat a grid array, it'll go all the way up and startup somewhat in the middle even above the top of my design… I can send the design to the developer.

**Comment by LightBurnSoftware** [comment]
We'll need more specifics - What laser controller are you using, and what "start from" setting are you using, for starters.

**Comment by funinthefalls** [comment]
If you have any more questions, the LightBurn Facebook page is the best place to ask.
