### ISSUE TITLE
Resizing an image does not appear to be uniform

### ISSUE THREAD

**Issue by davegalesr** [LightBurnSoftware/Documentation#16]
When I resize am image for raster engraving, it does not end up as uniform - it loses it's aspect ratio.  I have tried both the shift and ctrl key options ant the image appears to be correct on the workspace but the engraved image has lost some width and the engraved image is skinnier than the workspace image.

**Comment by davegalesr** [comment]
I am sending the g-code to a gerbil board if that makes a difference

**Comment by LightBurnSoftware** [comment]
This is the place for documentation specific issues.  If the image is correct in the view, but not when output, does a simple square exhibit the same behavior? Create a 50mm square, cut it at low power (just mark the material) and measure it. If it's not 50 x 50 you probably have to adjust your steps per mm setting in your hardware.

If you want to follow up, please post in our FB support group, with a photo of the output.

**Comment by davegalesr** [comment]
Thanks - closing...
