### ISSUE TITLE
set or clear a custom origin buttons do nothing

### ISSUE THREAD

**Issue by rocketcol** [LightBurnSoftware/Documentation#22]
Having problems with setting origin using the buttons.
I assume you jog to where you want your origin to be then click " set origin" 
but makes no difference to the position, just stays the same.
HELP

**Comment by LightBurnSoftware** [comment]
Have you read the docs on origin and coordinates? It’s likely that you’re running in “Absolute Coords” instead of “User Origin” or “Current Position”.

Also, you’ll get faster feedback on our FB support page.
