### ISSUE TITLE
Linux Installation Documentation is Wanting

### ISSUE THREAD

**Issue by smellyfis** [LightBurnSoftware/Documentation#27]
I am trying to install LightBurn as system executable as my family all log into the computer with different accounts. My questions are where do I install it, typically "packaged products" go in /opt/<package> and then the bin of the package gets added to the system path, and individual user configurations go into there home directory. Also, where does the .config folder go? What is it's purpose? Also, what do all the conf and ini files do and how safe are they to change?

**Comment by LightBurnSoftware** [comment]
I know next to nothing about Linux, and it was a minor miracle that I was able to produce a build and get it deployed. There is no install required - it's a self contained folder you can put anywhere. As to the "what are all the .ini files for?" I only produce the prefs.ini file. It can always be rebuilt, but it stores all your cut settings, window layout, and device profiles, so corrupting it would lose those.
