### ISSUE TITLE
ABILITY TO EDIT HOME BUTTON COMMAND

### ISSUE THREAD

**Issue by marvinlange** [LightBurnSoftware/Documentation#28]
If I hit the home button using marlin it moves home wile leaving laser on I solved temp using macro but it would be nice if I could add M107 command on the home button prior to G28 kind of the same way edit macros.  also stop leaves laser on needs to send M107

Thanks
GOD Bless
Marvin
marvinlange@gmail.com

**Comment by LightBurnSoftware** [comment]
This should be resolved in the latest release, 0.8.02. In the future, please use the documentation repo only for documentation bugs, and submit software issues directly to us via our support email.  We don't check this very often.
