### ISSUE TITLE
Add details about color and layer handling for importing of vectors

### ISSUE THREAD

**Issue by gndprx** [LightBurnSoftware/Documentation#3]
The following file has a TODO for adding documentation about color and layer handling. Per a Facebook discussion with Jason, this should be held until all of the functionality can be built out.

https://github.com/LightBurnSoftware/Documentation/blob/master/ImportingExternalVectors.md

Relevant Facebook discussion: 
https://www.facebook.com/groups/141367793135831/159096491362961/

**Comment by funinthefalls** [comment]
Seems complete now
