### ISSUE TITLE
Centre workspace

### ISSUE THREAD

**Issue by Mungbeanz** [LightBurnSoftware/Documentation#30]
I was wanting to know is it possible to do center homing of the workplace coordinate system.
I have been working around this by setting the artwork centered at machine 0,0. But this only show part of the grid and gives out of bounds errors.

[https://i.screenshot.net/vrrkzul](url)

I work mostly in CNC milling and have adapted most of my methods and work processes to a centre homing method for my workspace.

Is it possible to have a centre homing workspace during design?
Is it possible to change the grid system to adapt negative coordinates?

**Comment by funinthefalls** [comment]
Please post your question on the facebook LightBurn group or the google+ group. This area is for document related things like missing documentation.
Thanks

**Comment by LightBurnSoftware** [comment]
Mung - It't not possible to use negative coordinates directly with LightBurn, however a workspace offset will allow you to work with a normal front-left origin.

See here for details:  https://github.com/LightBurnSoftware/Documentation/blob/master/CommonGrblSetups.md

And yes, this page is for documentation issues, not bug reporting.  Please use one of our forums or support email in the future.
