### ISSUE TITLE
Content without a home - Device connection details from help file

### ISSUE THREAD

**Issue by gndprx** [LightBurnSoftware/Documentation#4]
This was pulled from the help file and needs an appropriate home in the documentation. Do we create a troubleshooting section? 

"If you need to reset your device connection, simply open the devices menu, then hit ok.  LightBurn does a full disconnect / reconnect cycle when you click ok in the devices menu."

**Comment by funinthefalls** [comment]
I think a troubleshooting section would be appropriate.

**Comment by gndprx** [comment]
Done and done.
